/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderFoodDetails.java
 *
 * Created on Jul 10, 2016, 6:57:03 PM
 */
package OrderBooking;

import db.Dbcon;

/**
 *
 * @author kakes
 */
public class OrderFoodDetails extends javax.swing.JFrame {

    /**
     * Creates new form OrderFoodDetails
     */
    public OrderFoodDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    int userid;

    public OrderFoodDetails(String id) {
        initComponents();
        this.setLocationRelativeTo(null);

        int u_id = Integer.parseInt(id);

        System.out.println(u_id);
        userid = u_id;
        System.out.println(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        mango = new javax.swing.JCheckBox();
        lemon = new javax.swing.JCheckBox();
        injiCurry = new javax.swing.JCheckBox();
        pachadi = new javax.swing.JCheckBox();
        oolan = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        paripp = new javax.swing.JCheckBox();
        suchi_gothamb = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        kichadi = new javax.swing.JCheckBox();
        thoran = new javax.swing.JCheckBox();
        kaalan = new javax.swing.JCheckBox();
        aviyal = new javax.swing.JCheckBox();
        masaalaCurry = new javax.swing.JCheckBox();
        kootuCurry = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        rasam = new javax.swing.JCheckBox();
        sambaaram = new javax.swing.JCheckBox();
        pappadam = new javax.swing.JCheckBox();
        paalada = new javax.swing.JCheckBox();
        njalipoovan = new javax.swing.JCheckBox();
        saambar = new javax.swing.JCheckBox();
        kattiParipp = new javax.swing.JCheckBox();
        kaaya_varuthath = new javax.swing.JCheckBox();
        sarkkara_puratti = new javax.swing.JCheckBox();
        water = new javax.swing.JCheckBox();
        vazhayila = new javax.swing.JCheckBox();
        paper_roll = new javax.swing.JCheckBox();
        paper_glass = new javax.swing.JCheckBox();
        ellunda = new javax.swing.JCheckBox();
        paripp_vada = new javax.swing.JCheckBox();
        vilambu_pathrangal = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("FOOD DETAILS");

        jLabel2.setText("Rice");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kuthari", "vella choru" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Pickle");

        mango.setSelected(true);
        mango.setText("Mango");

        lemon.setSelected(true);
        lemon.setText("Lemon");

        injiCurry.setSelected(true);
        injiCurry.setText("Injicurry/Puliyinji");

        pachadi.setSelected(true);
        pachadi.setText("Pachadi");

        oolan.setSelected(true);
        oolan.setText("Oolan");

        jLabel4.setText("Paayasam");

        paripp.setSelected(true);
        paripp.setText("paripp");

        suchi_gothamb.setSelected(true);
        suchi_gothamb.setText("Suchi Gothamb");

        jLabel5.setText("Other Items");

        kichadi.setSelected(true);
        kichadi.setText("Kichadi");

        thoran.setSelected(true);
        thoran.setText("Thoran");

        kaalan.setSelected(true);
        kaalan.setText("Kaalan");

        aviyal.setSelected(true);
        aviyal.setText("Aviyal");

        masaalaCurry.setSelected(true);
        masaalaCurry.setText("MasaalaCurry");

        kootuCurry.setSelected(true);
        kootuCurry.setText("KootuCurry");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        rasam.setSelected(true);
        rasam.setText("Rasam");

        sambaaram.setSelected(true);
        sambaaram.setText("Sambaaram");

        pappadam.setSelected(true);
        pappadam.setText("Pappadam");

        paalada.setSelected(true);
        paalada.setText("Paalada");

        njalipoovan.setSelected(true);
        njalipoovan.setText("NjaliPoovan Pazham");

        saambar.setSelected(true);
        saambar.setText("Sambaar");

        kattiParipp.setSelected(true);
        kattiParipp.setText("KattiParipp");

        kaaya_varuthath.setSelected(true);
        kaaya_varuthath.setText("Kaaya Varuthath");

        sarkkara_puratti.setSelected(true);
        sarkkara_puratti.setText("Sarkkara Puratti");

        water.setSelected(true);
        water.setText("Water");

        vazhayila.setSelected(true);
        vazhayila.setText("Vaazhayila");

        paper_roll.setSelected(true);
        paper_roll.setText("Paper Roll");

        paper_glass.setSelected(true);
        paper_glass.setText("Paper Glass");

        ellunda.setSelected(true);
        ellunda.setText("Ellu Unda");

        paripp_vada.setSelected(true);
        paripp_vada.setText("Paripp Vada");

        vilambu_pathrangal.setSelected(true);
        vilambu_pathrangal.setText("Vilambu Paathrangal");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mango, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paripp)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(suchi_gothamb)
                                .addGap(42, 42, 42)
                                .addComponent(paalada))
                            .addComponent(lemon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aviyal)
                    .addComponent(injiCurry)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masaalaCurry)
                            .addComponent(pachadi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oolan)
                            .addComponent(kootuCurry)))
                    .addComponent(kattiParipp)
                    .addComponent(kichadi)
                    .addComponent(thoran)
                    .addComponent(kaalan))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saambar)
                    .addComponent(sambaaram)
                    .addComponent(pappadam)
                    .addComponent(njalipoovan)
                    .addComponent(kaaya_varuthath)
                    .addComponent(water)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sarkkara_puratti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paper_roll)
                    .addComponent(paper_glass)
                    .addComponent(paripp_vada)
                    .addComponent(vilambu_pathrangal)
                    .addComponent(ellunda)
                    .addComponent(vazhayila)
                    .addComponent(rasam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mango)
                    .addComponent(lemon)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(paripp)
                    .addComponent(suchi_gothamb)
                    .addComponent(paalada))
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saambar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sambaaram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pappadam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(njalipoovan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kaaya_varuthath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sarkkara_puratti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(water)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paper_roll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paper_glass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paripp_vada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vilambu_pathrangal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ellunda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vazhayila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rasam)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pachadi)
                                    .addComponent(oolan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(masaalaCurry)
                                    .addComponent(kootuCurry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(injiCurry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kichadi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thoran, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kaalan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aviyal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kattiParipp)))
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

       // JCheckBox jCheckBox1=new JCheckBox();

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dbcon dbcon = new Dbcon();
        String kuthari = "", vellachoru = "";
        String rice = jComboBox1.getSelectedItem().toString();
       
        boolean f1 = injiCurry.isSelected();
        boolean f2 = lemon.isSelected();
        boolean f3 = mango.isSelected();
        boolean f4 = pachadi.isSelected();
        boolean f5 = oolan.isSelected();
        boolean f6 = kichadi.isSelected();
        boolean f7 = thoran.isSelected();
        boolean f8 = kaalan.isSelected();
        boolean f9 = aviyal.isSelected();
        boolean f10 = masaalaCurry.isSelected();
        boolean f11 = kootuCurry.isSelected();
        boolean f12 = kattiParipp.isSelected();
        boolean f13 = saambar.isSelected();
        boolean f14 = rasam.isSelected();
        boolean f15 = sambaaram.isSelected();
        boolean f16 = pappadam.isSelected();
        boolean f17 = njalipoovan.isSelected();
        boolean f18 = kaaya_varuthath.isSelected();
        boolean f19 = sarkkara_puratti.isSelected();
        boolean f20 = paalada.isSelected();
        boolean f21 = suchi_gothamb.isSelected();
        boolean f22 = paripp.isSelected();
        boolean f23 = water.isSelected();
        boolean f24 = vazhayila.isSelected();
        boolean f25 =paper_roll.isSelected();
        boolean f26 = paper_glass.isSelected();
        boolean f27 = ellunda.isSelected();
        boolean f28 = paripp_vada.isSelected();
        boolean f29 = vilambu_pathrangal.isSelected();
       

        dbcon.insert("insert into tbl_food(order_id,rice_type,injicurry,lemon_pickle,mango_pickle,pachadi,oolan,kichadi,thoran,kaalan,aviyal,masalacurry,kootucurry,kattiparipp,saambar,rasam,sambaaram,pappadam,njalipoovan,kaayavaruthath,sarkkarapuratti,paalada,suchigothamb_paayasam,paripp_payasam,water,vazhayila,paper_roll,paper_glass,ellunda,paripp_vada,vilambu_paathrangal)values('" + userid + "','" +rice+ "','"+f1+"','"+f2+"','"+f3+"','"+f4+"','"+f5+"','"+f6+"','"+f7+"','"+f8+"','"+f9+"','"+f10+"','"+f11+"','"+f12+"','"+f13+"','"+f14+"','"+f15+"','"+f16+"','"+f17+"','"+f18+"','"+f19+"','"+f20+"','"+f21+"','"+f22+"','"+f23+"','"+f24+"','"+f25+"','"+f26+"','"+f27+"','"+f28+"','"+f29+"')");
       //qry);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFoodDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFoodDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFoodDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFoodDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OrderFoodDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aviyal;
    private javax.swing.JCheckBox ellunda;
    private javax.swing.JCheckBox injiCurry;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox kaalan;
    private javax.swing.JCheckBox kaaya_varuthath;
    private javax.swing.JCheckBox kattiParipp;
    private javax.swing.JCheckBox kichadi;
    private javax.swing.JCheckBox kootuCurry;
    private javax.swing.JCheckBox lemon;
    private javax.swing.JCheckBox mango;
    private javax.swing.JCheckBox masaalaCurry;
    private javax.swing.JCheckBox njalipoovan;
    private javax.swing.JCheckBox oolan;
    private javax.swing.JCheckBox paalada;
    private javax.swing.JCheckBox pachadi;
    private javax.swing.JCheckBox paper_glass;
    private javax.swing.JCheckBox paper_roll;
    private javax.swing.JCheckBox pappadam;
    private javax.swing.JCheckBox paripp;
    private javax.swing.JCheckBox paripp_vada;
    private javax.swing.JCheckBox rasam;
    private javax.swing.JCheckBox saambar;
    private javax.swing.JCheckBox sambaaram;
    private javax.swing.JCheckBox sarkkara_puratti;
    private javax.swing.JCheckBox suchi_gothamb;
    private javax.swing.JCheckBox thoran;
    private javax.swing.JCheckBox vazhayila;
    private javax.swing.JCheckBox vilambu_pathrangal;
    private javax.swing.JCheckBox water;
    // End of variables declaration//GEN-END:variables
}
